---
title: "Spotify"
author: "Silvia Ferrer, Marc Fortó, Ignacio Lloret, Iñigo Pikabea, Max Ticó and Rong Xing"
date: "2023-10-05"
output: 
  html_document:
    toc: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(magrittr)
library(tidyverse)
library(arrow)
library(FactoMineR)
```

## Lectura


```{r lectura, include=FALSE}
df <- readr::read_csv("../Spotify_Youtube.csv")

df2 <- readr::read_csv("../genres_v2.csv")

df2$Uri <- df2$uri
df2
df2 <- df2 %>% select("Uri","genre","mode","time_signature","type")


df3 <- merge(df, df2, by = c("Uri"))


df <- df3
```
## EDA before preprocessing

```{r EDA b prpr}
library(DataExplorer)

create_report(df)
```


## Preprocessing


```{r preprocessing, include=FALSE}
source("../scripts/preprocessing.r")
```


## EDA after preprocessing

```{r EDA b prpr}
df_wk_i <- readRDS("preprocessing.Rdata")

create_report(df_wk_i,   config = configure_report(add_plot_prcomp = FALSE))
```

## PCA

```{r PCA}
source("../scripts/PCA.r")
```

## MCA

```{r PCA}
source("../scripts/MCA_project.r")
```

## Hierarchical Clustering
```{r}
df_wk_i <- readRDS("preprocessing.Rdata")
df_ <- df_wk_i %>% 
  select("Album_type","Danceability","Energy","Key","Loudness",
         "Speechiness","Acousticness","Instrumentalness", "Liveness", "Valence",
         "Tempo","Duration_ms","scaled_stream", "scaled_views", "genre","mode","time_signature",
         "type"
         )
df_wk_i %>% names()
d <- dist(df_)
h1 <- hclust(d,method="ward")  # NOTICE THE COST
plot(h1)


c1 <- cutree(h1,10)

df_$cluster <- c1 %>% as.factor

catdes(df_, num.var=which(names(df_)=='cluster'))

df_ %>%
  ggplot() +
  geom_bar(aes(x = cluster, fill = genre), stat = "count")

```


